### ISSUE TITLE
MathJax does not work together with MermaidJS

### ISSUE THREAD

**Issue by kuznero** [rust-lang-nursery/mdBook#1007]
Here is an example `boot.toml`:

```toml
[book]
authors = ["Roman Kuznetsov"]
language = "en"
multilingual = false
src = "src"
title = "Coursera: Data Structures and Algorithms"

[build]
create-missing = false
use-default-preprocessors = true  # enables the "links" preprocessor

# NOTE: as of now MathJax does not seem to work nicely with MermaidJS (so, choosing MathJax for now)

# [preprocessor.mermaid]
# command = "mdbook-mermaid"
# renderer = ["html"]

[output.html]
# additional-css = ["assets/mermaid.css", "assets/override.css", "assets/lightfair.css"]
additional-css = ["assets/override.css", "assets/lightfair.css"]
# additional-js = ["assets/mermaid.min.js", "assets/mermaid-init.js"]
mathjax-support = true
theme = "assets"

[output.html.playpen]
editable = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
```
