### ISSUE TITLE
Reduce dependency tree

### ISSUE THREAD

**Issue by bheisler** [rust-lang-nursery/mdBook#1017]
Hey, thanks for the work on mdbook!

Would it be possible to try to prune mdBook's dependency tree?

My documentation build in Travis needs to download and compile ~300 crates to install mdbook on every build. This takes a long time (~10 minutes for mdbook). I then install `mdbook-linkcheck`, which depends on mdbook and so it has to download and recompile the whole tree again. The long compile times also make it more painful to install and use mdbook normally, or to update from older versions.

**Comment by ehuss** [comment]
Binary releases are made available at https://github.com/rust-lang-nursery/mdBook/releases, which is what I use to reduce CI time.  That may not help with `mdbook-linkcheck`, though.  There is also a number of Cargo features which you can turn off to reduce the compile time (almost twice as fast with all of them off).

There are a few deps that could maybe be trimmed, but they will unlikely make a noticeable impact. The slower dependencies (syn, serde, regex, clap) can't really be removed.

You can also try to take advantage of CI caching.  sccache is one option.  You can also just cache `~/.cargo/bin`.  I've also been experimenting with the unstable `-Z install-upgrade` cargo option to make this easier (such as [here](https://github.com/rust-lang-nursery/edition-guide/blob/e58bc4ca104e890ac56af846877c874c432a64b5/.travis.yml#L5)).

**Comment by bheisler** [comment]
Ah, I hadn't known about the cargo features; that will help.

I currently force-install on every build to make sure that it has the latest version, so caching doesn't really help there. I'll keep an eye on the `install-upgrade` option; hopefully it's stabilized soon.

**Comment by Lokathor** [comment]
@bheisler until then try something like this

```yml
cache:
  cargo

before_script:
  - test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update
  - test -x $HOME/.cargo/bin/mdbook || cargo install mdbook
  - cargo install-update -a
```
