### ISSUE TITLE
Do not ignore `HtmlConfig` syntax errors silently

### ISSUE THREAD

**Issue by TjeuKayim** [rust-lang-nursery/mdBook#1032]
`HtmlConfig` parsing error are silently ignored and the default values are used. This makes it hard for users to troubleshoot typos in their `book.toml`.

I tried this `book.toml`:

```toml
[output.html]
default-theme = "navy"
curly-quotes = "true"
# should have been: curly-quotes = true
```

*I expected to see this happen*: mdBook displays a warning or error message when building if the configuration contains a syntax error, like
`[WARNING] (mdbook::book): Configuration value for 'output.html.curly-quotes' is invalid, expected a boolean but got string "true".`
It applies the valid config nodes and sets the `default-theme` to `navy`, but uses the default value for `curly-quotes`.

*Instead, this happened*: The build succeeds without any warning, and ignores the valid config nodes under `output.html`. So the `default-theme` falls back to default.

## Meta

mdBook version b4bb44292d707c720dc75851500b3249d3a93ad3
