### ISSUE TITLE
[Discussion] New renderers design

### ISSUE THREAD

**Issue by azerupi** [rust-lang-nursery/mdBook#149]
The idea, is to separate mdBook into more clearly defined "modules". *(not Rust modules)*

- ***core***: The core handles the internal representation. It parses the configuration file and the summary file. It should contain only generic metadata and the structure of the book (see #146 for more discussion)
- ***renderers***: Renderers are self contained modules that consume the book as stored in ***core*** and render it to one specific target (e.g. html, EPUB, pdf, ...)

Renderers could need additional metadata or offer specific settings that could (and should) not be represented in the core internal representation. For that purpose, the configuration file will allow sub-sections for the renderer specific options. Imagine:

```toml
[outputs.html]
path = "book/"
favicon = "src/img/favicon.png"

[outputs.epub]
isbn = "978-0-9999999-9-9"
uuid = "58dce2ac-7aec-45c3-a6de-903a30061545"
version = "1.0"

# ...
```

Those configuration parameters will be passed down to the renderer, it's his job to actually make sense of those settings.

Essentially `MDBook` + `[outputs.renderer]` => `Renderer` = `Output`
