### ISSUE TITLE
Mobile browsers zoom in when horizontal (CSS missing `text-size-adjust` property)

### ISSUE THREAD

**Issue by aaaxx** [rust-lang-nursery/mdBook#184]
The CSS is missing a pretty standard piece of code (e.g. it's used in Normalize.css and other templates) that prevents mobile browser from zooming in when turned horizontally:

```css
html {
    -webkit-text-size-adjust: 100%;
        -ms-text-size-adjust: 100%;
}
```

![mobile browser example](https://cloud.githubusercontent.com/assets/6186480/20854243/62f3be98-b8f2-11e6-98f6-4a0ec0a0bf5c.png)
