### ISSUE TITLE
Don't use "px" as font size unit

### ISSUE THREAD

**Issue by StefanoD** [rust-lang-nursery/mdBook#203]
Displays have different resolutions, so it is not recommended using _px_ as font-size unit. It is better to use _em_ or _%_.
i looked at the new book version of [Rust Book](http://rust-lang.github.io/book/) and I could find one font-size declaration using _px_:

```CSS
.menu-title {
  display: inline-block;
  font-weight: 200;
  font-size: 20px;
  //...
}
```
Maybe this was made on purpose, maybe not. I'm not really the web-dev guy. :)
