### ISSUE TITLE
Footnotes have no styles

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/mdBook#210]
A simple

```css
div.footnote-definition p {
       display: inline;
}
```

makes them look kind of okay : 

<img width="568" alt="theme" src="https://cloud.githubusercontent.com/assets/27786/23149265/ba15f042-f7b8-11e6-9767-c3bae61f1eb5.png">

But I wonder if we can do better.
