### ISSUE TITLE
Document the Ace Editor

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-lang-nursery/mdBook#521]
#338 added the ace editor but we didn't really document it in the [user guide]. There are currently two parts to making code snippets editable, first you need to enable editing in your `book.toml`, then you need to add an `editable` annotation to your code blocks.

The config file:

```toml
[output.html.playpen]
editor = "./path/to/ace/editor"  # defaults to using the ace editor
editable = false # defaults to false
```

Making a specific code snippet editable

    ```rust,editable
    use std::fs::File;
    File::open("foo.txt").unwrap();
    ```

[user guide]: https://rust-lang-nursery.github.io/mdBook/
