### ISSUE TITLE
Top bar hides section headings when visiting perma links

### ISSUE THREAD

**Issue by Emerentius** [rust-lang-nursery/mdBook#634]
When visiting the chapter title or the smaller subsection titles via permalinks such as [this chapter title](https://doc.rust-lang.org/nightly/book/second-edition/ch09-02-recoverable-errors-with-result.html#recoverable-errors-with-result) or [this subsection](https://doc.rust-lang.org/nightly/book/second-edition/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-), the title will be hidden by the top bar. There is no issue for sections ([example](https://doc.rust-lang.org/nightly/book/second-edition/ch09-02-recoverable-errors-with-result.html#propagating-errors))

In case you're seeing something different, here's a screenshot

![screenshot2](https://user-images.githubusercontent.com/9992929/36880522-6c68b414-1dc9-11e8-87aa-52a36844dd45.png)

**Comment by Michael-F-Bryan** [comment]
@sorin-davidoi could this be something to do with how the header floats on top of the page?

**Comment by sorin-davidoi** [comment]
Yes, most likely. Will take a look in the following days.

**Comment by sts10** [comment]
Just checking: Are there any updates/fixes/work-arounds for this issue?

**Comment by sorin-davidoi** [comment]
@sts10 I think changes would be needed in [`autoHideMenu`](https://github.com/rust-lang-nursery/mdBook/blob/master/src/theme/book.js#L583) - possibly have a boolean indicate wether the user has ever scrolled (false by default, set to true on the first `scroll` event) and don't show the menubar if the user has never scrolled (which is the case when they first enter a page).

**Comment by sts10** [comment]
OK, my fix of choice at this point is, in [chrome.css on line 73](https://github.com/rust-lang-nursery/mdBook/blob/b4538da9c3e8a02551fd0d34cfc7c4ed0d1410e0/src/theme/css/chrome.css#L73), to change

```css
html:not(.sidebar-visible) #menu-bar:not(:hover).folded > #menu-bar-sticky-container {
    transform: translateY(-60px);
}
```

to 

```css
#menu-bar:not(:hover).folded > #menu-bar-sticky-container {
    transform: translateY(-60px);
}
```

This change ensures that the top menu will be "hidden" until the user scrolls up, _even when the sidebar is opened_. This is a pretty good solution for my needs, but I'm not sure it's a change that should be made to the default theme.
