### ISSUE TITLE
Support Lua syntax highlighting

### ISSUE THREAD

**Issue by tversteeg** [rust-lang-nursery/mdBook#668]
I'm new to using mdBook so maybe I'm missing something but when I use the following code format nothing happens:

    ```lua
    local test = 10
    local test2 = {
      a: 10,
      b: 20
    }
    ```

How can I get correct syntax highlighting for Lua snippets?

**Comment by mattico** [comment]
mdBook uses highlight.js to do syntax highlighting. The version of hljs included with the default theme doesn't support lua highlighting. To add support for it:

1. Get a version of hljs with lua support https://highlightjs.org/download/
2. Rename it to `highlight.js` and put it in a directory somewhere
3. Add a theme key to your `Book.toml`: 
   ```toml
   [output.html]
   theme = "theme" # the name of the directory you put hljs in
   ```

Note that the theme path is relative to where you run `mdbook`, not relative to your `Book.toml`.
