### ISSUE TITLE
Numbering in section headings

### ISSUE THREAD

**Issue by thejpster** [rust-lang-nursery/mdBook#723]
Is it possible to enable numbering of section headings in the output? Without it, the print preview can be a little confusing as you have to rely entirely on the heading styles to work out which are sub-headings and which are top-level headings.

**Comment by martinjaeger** [comment]
I agree that this would be a nice feature.

**Comment by your-diary** [comment]
Any updates?

**Comment by your-diary** [comment]
OK, I could customize [`general.css`](https://rust-lang.github.io/mdBook/format/theme/index.html).

1. `mdbook init --theme` to create a new book.

2. Move `theme/` to your existing book directory.

3. Append the lines below to `theme/css/general.css`.

```css
body {
    counter-reset: section -1;
}
h1 {
    counter-reset: subsection 0;
}
h1::before {
    counter-increment: section;
    content: counter(section) ": ";
}
h2::before {
    counter-increment: subsection;
    content: counter(section) "." counter(subsection) ": ";
}
```

4. Build
