### ISSUE TITLE
additional-js files are not resolved relative to book root

### ISSUE THREAD

**Issue by wirelyre** [rust-lang-nursery/mdBook#774]
Since #603 removed the `<base>` tag, additional-js files such as this:

```toml
[output.html]
additional-js = ["some-file.js"]
```

are broken in any book subdirectories.
