### ISSUE TITLE
Add "additional links" option

### ISSUE THREAD

**Issue by Bassetts** [rust-lang-nursery/mdBook#810]
Opening this issue to discuss/explore adding "additional links" functionality which was discussed in https://github.com/rust-lang-nursery/mdBook/pull/802#issuecomment-429806873.

We should let the users provide multiple links to add to the right buttons area, allowing them to specify the title, icon, and href. This will genericise the `git_repository_url` and `git_repository_icon` options.

@Michael-F-Bryan mentioned the configuration could look like
```toml
[[output.html.links]]
title = "The GitHub Repository"
# the icon starts with `fa-` so assume it's FontAwesome
icon = "fa-github"
href = "https://github.com/my-user/my-repo"

[[output.html.links]]
title = "My Website"
# Parses as a URL, insert an `<img />` tag
icon = "https://example.com/my-logo.png"
href = "https://example.com/"
```

My thought is that if the icon doesn't look like a url then we should treat it as a FontAwesome icon class, rather than the other way around. I am fairly new to Rust though, so am not sure if this adds a lot of complexity.

The resulting Html config would then look like

```rust
struct HtmlConfig {
  ...
  /// Icons to be rendered across the top
  links: Vec<Link>,
}

struct Link {
  icon: Icon,
  title: String,
  href: Url,
}

enum Icon {
  FontAwesome(String),
  Url(Url),
}

impl Deserialize for Icon {
  // add appropriate logic for parsing a string as either 
  // a FontAwesome icon or a URL.
}
```

Should we leave the current `git_repository_url`/`git_repository_icon` options, or should this functionality replace those completely? If it is decided that they should remain, what order should we output the print button, github button, and additional links in the default theme?
