### ISSUE TITLE
Print book version

### ISSUE THREAD

**Issue by fabioluciano** [rust-lang-nursery/mdBook#987]
There is any way to print the version of the book?

``` toml
[book]
authors = ["Fábio Luciano"]
multilingual = true
src = "src"
title = "Foo"
version = "1.0.1"
```

how to print version in my documentation?
